#!/bin/bash
addr=$1
cntlist="countries"
which nc > /dev/null 2>&1
      if [ "$?" -eq "1" ]; then
      echo "Netcat Dependency Missing"
      exit 1
      fi
which wget > /dev/null 2>&1
      if [ "$?" -eq "1" ]; then
      echo "wget Dependency Missing"
      exit 1
      fi
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
if [ $? -ne 0 ]; then
echo "Opps , not connected to Internet"
exit 1
fi
if [[ -z "$addr" ]] 
then
echo "Ipcountry"
echo "-------------------------------------------------"
echo "Switches :"
echo "$0 172.217.168.174 (to retrieve country from IP)"
echo "$0 -h (This help)"
echo "-------------------------------------------------"
echo "Thanks to (Individual) LQ for the help" 
echo "-------------------------------------------------" 
echo "This Scripts uses Dnslytics.com "
echo ""
exit 1
fi 
if [[ "$addr" == "-h" ]] 
then
echo "Ipcountry"
echo "-------------------------------------------------"
echo "Switches :"
echo "$0 172.217.168.174 (to retrieve country from IP)"
echo "$0 -h (This help)"
echo "-------------------------------------------------"
echo "Thanks to (Individual) LQ for the help" 
echo "-------------------------------------------------" 
echo "This Scripts uses Dnslytics.com "
echo ""
exit 1
fi 
if [[ ! -f "$cntlist" ]]
then
wget https://raw.githubusercontent.com/peterpt/ipcountry/master/countries
fi
site="https://dnslytics.com/ip"
addr=$1
html=$(wget -qO - "$site/$addr")
location_line=$(grep -m1 -oE '\btd><td>([^<]+)<\b' <<< "$html")
country=$(grep -m1 -o '\([A-Z][A-Z]\)' <<< "$location_line")
echo $country
cntname=$(grep " $country " < "$cntlist" | awk '{$1=$2="";print$0}')
echo $cntname

